# application Sales Man Management
Name = input("Enter salesman Name :-")
Id = input("Enter Salesman Id :-")
Route = input("Enter Source Route_1 :-")
Route_1 = input("Enter Destination Route :-")
Joining_Date = input("Enter Salesman Joining Date :-")
Current_Date = input("Enter Current Date :-")

Salesman_Salary = int(input("Enter Salesman Salary :"))
Total_Stock = int(input("Enter Total Stock :"))
Today_Sale = int(input("Enter Today Sale:-"))

price1 = (Total_Stock * 500)
Total_Comission = (Today_Sale * 500 * 0.1)
Total_Income_Of_Salesman = Total_Comission + Salesman_Salary

print("*" * 50)
print('\tName:-', Name)
print("*" * 50)
print("\tID:-", Id)
print("*" * 50)
print("\tRoute:-", Route)
print("*" * 50)
print("\tTo")
print("*" * 50)
print("\tRoute_1:-", Route_1)
print("*" * 50)
print("\tJoining-Date:-", Joining_Date)
print("*" * 50)
print("\tCurrent-Date:-", Current_Date)
print("*" * 50)
print("\tSalesMan Salary :-", Salesman_Salary)
print("*" * 50)
print("\tTotal-Stock:-", Total_Stock)
print("*" * 50)
print("\tToday-Sale:-", Today_Sale)
print("*" * 50)
print("\tPrice-1:-", price1)
print("*" * 50)
print("\tTotal-Commision:-", Total_Comission)
print("*" * 50)
print("\tTotal Income of Salesman:-", Total_Income_Of_Salesman)
print("*" * 50)
